server:
  port: 80
spring:
  application:
    name: cloud-order-service

eureka:
  instance:
    hostname: localhost #eureka服务端的实例
    instance-id: cloud-order-service
  client:
    register-with-eureka: true #自己作为client需要注册到eureka中去
    fetch-registry: true #ture表示需要从Eureka中抓取已有的信息 默认为true
    service-url: #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002:7002.com/eureka/,http://eureka7003:7003.com/eureka/ # 集群模式
      #defaultZone: http://eureka7003:7003.com/eureka/ # 不搭建集群 单机 指
