server:
  port: 8401
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos服务注册中心的地址
    sentinel:
      transport:
        dashboard: localhost:8080  #服务监控的地址 降级 限流 熔断
        port: 8719  #默认是8719端口 如果8719被占用则会往后+1扫描


management:
  endpoints:
    web:
      exposure:
        include: '*'