server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能 利用微服务的名称来获取url
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          #uri: http://localhost:8081
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
        - id: payment_route2
          #          uri: http://localhost:8081
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/** #断言,路径相匹配的进行路由
            - After=2020-05-01T17:27:13.820+08:00[Asia/Shanghai]
            #- Cookie=username,zzyy #两个值的意思是第一个是cookie的名称 第二个是这个名称的正则表达式
            #- Header=X-Request-Id,\d+ # 请求头需要带上X-Request-Id  且符合数字的正则 断言为true才会继续访问
eureka:
  instance:
    hostname: localhost #eureka服务端的实例
    instance-id: cloud-gateway-service
    prefer-ip-address: true
  client:
    register-with-eureka: true #自己作为client需要注册到eureka中去
    fetch-registry: true #ture表示需要从Eureka中抓取已有的信息 默认为true
    service-url: #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/
