server:
  port: 8001
spring:
  application:
    name: cloud-provider-hystrix-payment
eureka:
  client:
    register-with-eureka: true #自己作为client需要注册到eureka中去
    fetch-registry: true #ture表示需要从Eureka中抓取已有的信息 默认为true
    service-url: #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/
