server:
  port: 80

spring:
  application:
    name: cloud-provider-hystrix-order
eureka:
  client:
    register-with-eureka: true #自己作为client需要注册到eureka中去
    fetch-registry: true #ture表示需要从Eureka中抓取已有的信息 默认为true
    service-url: #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/
ribbon:
  ReadTimeout: 5000 #知道是建立连接所用的时间 适应于网络状况正常的情况下 两端链接所用时间
  ConnectTimeOut: 5000 #指的是建立连接后从服务的读取到可用资源所用的时间
feign:
  hystrix:
    enabled: true
